apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: [PVC-NAME]
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
