apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sim2real-challenge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Ti
  volumeMode: Filesystem
